"""Added Subgoals table

Revision ID: 02c961834b47
Revises: 30ca2d8649a6
Create Date: 2019-02-13 16:40:03.640630

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02c961834b47'
down_revision = '30ca2d8649a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subgoal',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('title', sa.String(length=140), nullable=False),
                    sa.Column('duedate', sa.DateTime(), nullable=True),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.Column('updated_at', sa.DateTime(), nullable=True),
                    sa.Column('goal_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['goal_id'], ['goal.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_subgoal_created_at'),
                    'subgoal', ['created_at'], unique=False)
    op.create_index(op.f('ix_subgoal_duedate'),
                    'subgoal', ['duedate'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_subgoal_duedate'), table_name='subgoal')
    op.drop_index(op.f('ix_subgoal_created_at'), table_name='subgoal')
    op.drop_table('subgoal')
    # ### end Alembic commands ###
