"""Renamed Goal.due_date into Goal.duedate

Revision ID: 30ca2d8649a6
Revises: 3ca12759cc66
Create Date: 2019-02-12 14:58:29.939919

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30ca2d8649a6'
down_revision = '3ca12759cc66'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('goal') as batch_op:
        batch_op.add_column(sa.Column('duedate', sa.DateTime(), nullable=True))
        batch_op.create_index(op.f('ix_goal_duedate'), [
                              'duedate'], unique=False)
        batch_op.drop_index('ix_goal_due_date')
        batch_op.drop_column('due_date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('goal') as batch_op:
        batch_op.add_column(
            sa.Column('due_date', sa.DATETIME(), nullable=True))
        batch_op.create_index('ix_goal_due_date',
                              ['due_date'], unique=False)
        batch_op.drop_index(op.f('ix_goal_duedate'))
        batch_op.drop_column('duedate')
    # ### end Alembic commands ###
