"""Added goals table

Revision ID: 3ca12759cc66
Revises: 1d5ebba109b2
Create Date: 2019-01-29 22:47:50.437689

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ca12759cc66'
down_revision = '1d5ebba109b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('goal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=140), nullable=False),
    sa.Column('description', sa.String(length=1024), nullable=True),
    sa.Column('due_date', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_goal_created_at'), 'goal', ['created_at'], unique=False)
    op.create_index(op.f('ix_goal_due_date'), 'goal', ['due_date'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_goal_due_date'), table_name='goal')
    op.drop_index(op.f('ix_goal_created_at'), table_name='goal')
    op.drop_table('goal')
    # ### end Alembic commands ###
